name: ci

on:
  push:
    branches:
      - "ci"
  schedule:
    - cron: '0 0 1 * *'

jobs:
  docker:
    strategy:
      matrix:
        version: ["2.6.8", "3.0.5", "3.1.3", "3.2.0"]
        image: ["almalinux:8", "almalinux:9"]
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set image name
        run: echo IMAGE_NAME=ameir/ruby:${{ matrix.version }}-$(echo ${{ matrix.image }} | tr ':' '-') >> $GITHUB_ENV
      - name: Set timestamp
        run: echo TIMESTAMP=$(date -u +%Y%m%d_%H%M%S) >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            IMAGE=${{ matrix.image }}
            RUBY_VERSION=${{ matrix.version }}
          cache-from: ${{ env.IMAGE_NAME }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}
            ${{ env.IMAGE_NAME }}-${{ env.TIMESTAMP }}
